# File system layout
# %APPVEYOR_BUILD_FOLDER%/
#   - depot_tools/ (in PATH)
#   - repo/
#       - pdfium/
#           - out/

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GYP_MSVS_VERSION: 2017
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  PATH: "%APPVEYOR_BUILD_FOLDER%/depot_tools;%PATH%"

install:
  - appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z -bd x depot_tools.zip -odepot_tools
  - gclient --version

before_build:
  - mkdir repo
  - cd repo
  - gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
  - gclient sync

build_script:
  - cd pdfium
  - mkdir out
  - copy %APPVEYOR_BUILD_FOLDER%\debug.args.gn out\args.gn
  - gn gen out
  - cd out
  - ninja pdfium

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir staging
  - move repo\pdfium\public staging\include
  - mkdir staging\x64\vs15\lib
  - move repo\pdfium\out\obj\pdfium.lib staging\x64\vs15\lib\pdfium.lib
  - 7z a pdfium-x64-vs15-debug.zip staging\*

artifacts:
  - path: pdfium-vs15-debug.zip
    name: PDFium for Visual Studio 2017, Debug
