# File system layout
# %APPVEYOR_BUILD_FOLDER%/
#   - depot_tools/ (in PATH)
#   - repo/
#       - pdfium/
#           - out/
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GYP_MSVS_VERSION: 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

build_script:
  - call build.bat

artifacts:
  - path: pdfium-*.zip
    name: PDFium library

deploy:
  - provider: GitHub
    tag: latest
    release: 'Latest build from master'
    description: "This is the latest build from the 'master' branch"
    prerelease: true
    force_update: true
    auth_token:
      secure: JH8IVbdgVLz16ZXQLO41jQ5OsC7wR8IMRPAzinrdqpvgfhe/btgtr1xZ5trO2Eux
    on:
      branch: master
