# File system layout
# %APPVEYOR_BUILD_FOLDER%/
#   - depot_tools/ (in PATH)
#   - repo/
#       - pdfium/
#           - out/
environment:
  PATH: "%APPVEYOR_BUILD_FOLDER%/depot_tools;%PATH%"
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GYP_MSVS_VERSION: 2017
  MY_TOOLSET: vs15

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

install:
  - appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z -bd x depot_tools.zip -odepot_tools
  - gclient --version

before_build:
  - mkdir repo
  - cd repo
  - gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
  - gclient sync

build_script:
  - cd pdfium
  - mkdir out
  - copy %APPVEYOR_BUILD_FOLDER%\args.gn out\args.gn
  - if "%CONFIGURATION%"=="Release" echo is_debug=false >> out\args.gn
  - if "%PLATFORM%"=="x86" echo target_cpu="x86" >> out\args.gn
  - type out\args.gn
  - gn gen out
  - cd out
  - ninja pdfium

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir staging
  - move repo\pdfium\LICENSE staging
  - move repo\pdfium\public staging\include
  - del staging\include\DEPS
  - del staging\include\README
  - set LIB_FOLDER=staging\%PLATFORM%\%MY_TOOLSET%\lib
  - mkdir %LIB_FOLDER%
  - move repo\pdfium\out\obj\pdfium.lib %LIB_FOLDER%
  - if "%CONFIGURATION%"=="Debug" rename %LIB_FOLDER%\pdfium.lib pdfiumd.lib
  - cd staging
  - if "%CONFIGURATION%"=="Debug" set SUFFIX=-debug
  - 7z a %APPVEYOR_BUILD_FOLDER%\pdfium-%PLATFORM%-%MY_TOOLSET%%SUFFIX%.zip *

artifacts:
  - path: 'pdfium-*.zip'
    name: PDFium library

deploy:
  - provider: GitHub
    tag: latest
    release: 'Latest build from master'
    description: "This is the latest build from the 'master' branch"
    prerelease: true
    force_update: true
    auth_token:
      secure: JH8IVbdgVLz16ZXQLO41jQ5OsC7wR8IMRPAzinrdqpvgfhe/btgtr1xZ5trO2Eux
    on:
      branch: master
