# File system layout
# %APPVEYOR_BUILD_FOLDER%/
#   - depot_tools/ (in PATH)
#   - repo/
#       - pdfium/
#           - out/

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GYP_MSVS_VERSION: 2017
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  PATH: "%APPVEYOR_BUILD_FOLDER%/depot_tools;%PATH%"

install:
  - appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z -bd x depot_tools.zip -odepot_tools
  - gclient --version

before_build:
  - mkdir repo
  - cd repo
  - gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
  - gclient sync

build_script:
  - cd pdfium
  - mkdir out
  - copy %APPVEYOR_BUILD_FOLDER%\debug.args.gn out\args.gn
  - gn gen out
  - cd out
  - ninja pdfium

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir staging
  - move repo\pdfium\public staging\include
  - mkdir staging\x64\vs15\lib
  - move repo\pdfium\out\obj\pdfium.lib staging\x64\vs15\lib\pdfium.lib
  - 7z a pdfium-x64-vs15-debug.zip staging\*

artifacts:
  - path: pdfium-vs15-debug.zip
    name: PDFium for Visual Studio 2017, Debug

cache:
  - depot_tools\win_tools-2_7_6_bin -> depot_tools\python_bin_reldir.txt
  - repo\pdfium\base -> repo\pdfium\DEPS
  - repo\pdfium\build -> repo\pdfium\DEPS
  - repo\pdfium\buildtools -> repo\pdfium\DEPS
  - repo\pdfium\testing\corpus -> repo\pdfium\DEPS
  - repo\pdfium\testing\gmock -> repo\pdfium\DEPS
  - repo\pdfium\testing\gtest -> repo\pdfium\DEPS
  - repo\pdfium\third_party\freetype\src -> repo\pdfium\DEPS
  - repo\pdfium\third_party\icu -> repo\pdfium\DEPS
  - repo\pdfium\third_party\instrumented_libraries -> repo\pdfium\DEPS
  - repo\pdfium\third_party\jinja2 -> repo\pdfium\DEPS
  - repo\pdfium\third_party\libjpeg_turbo -> repo\pdfium\DEPS
  - repo\pdfium\third_party\markupsafe -> repo\pdfium\DEPS
  - repo\pdfium\third_party\skia -> repo\pdfium\DEPS
  - repo\pdfium\third_party\yasm\source\patched-yasm -> repo\pdfium\DEPS
  - repo\pdfium\third_party\zlib -> repo\pdfium\DEPS
  - repo\pdfium\tools\clang -> repo\pdfium\DEPS
  - repo\pdfium\tools\gyp -> repo\pdfium\DEPS
  - repo\pdfium\tools\memory -> repo\pdfium\DEPS
  - repo\pdfium\v8 -> repo\pdfium\DEPS
