# File system layout
# %APPVEYOR_BUILD_FOLDER%/
#   - depot_tools/ (in PATH)
#   - repo/
#       - pdfium/
#           - out/
environment:
  PATH: "%APPVEYOR_BUILD_FOLDER%/depot_tools;%PATH%"
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GYP_MSVS_VERSION: 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

init:
  # Input
  - set PDFium_SOURCE_DIR=%APPVEYOR_BUILD_FOLDER%\repo\pdfium
  - set PDFium_BUILD_DIR=%PDFium_SOURCE_DIR%\out
  - set PDFium_PATCH=%APPVEYOR_BUILD_FOLDER%\shared_library.patch
  - set PDFium_ARGS=%APPVEYOR_BUILD_FOLDER%\args.gn
  # Output
  - set PDFium_NAME=pdfium
  - if "%CONFIGURATION%"=="Debug" PDFium_NAME=pdfiumd
  - set PDFium_STAGING_DIR=%APPVEYOR_BUILD_FOLDER%\staging
  - set PDFium_INCLUDE_DIR=%PDFium_STAGING_DIR%\include
  - set PDFium_BIN_DIR=%PDFium_STAGING_DIR%\%PLATFORM%\bin
  - set PDFium_DLL_FILE=%PDFium_BIN_DIR%\%PDFium_NAME%.dll
  - set PDFium_PDB_FILE=%PDFium_BIN_DIR%\%PDFium_NAME%.pdb
  - set PDFium_LIB_DIR=%PDFium_STAGING_DIR%\%PLATFORM%\lib
  - set PDFium_LIB_FILE=%PDFium_LIB_DIR%\%PDFium_NAME%.lib
  - set PDFium_ARTIFACT=%APPVEYOR_BUILD_FOLDER%\pdfium-%PLATFORM%.zip
  - if "%CONFIGURATION%"=="Debug" set PDFium_ARTIFACT=%APPVEYOR_BUILD_FOLDER%\pdfium-%PLATFORM%-debug.zip

install:
  - appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z -bd x depot_tools.zip -odepot_tools
  - gclient --version

before_build:
  - mkdir repo
  - cd repo
  - gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
  - gclient sync

build_script:
  - cd %PDFium_SOURCE_DIR%
  - patch < %PDFium_PATCH%
  - mkdir %PDFium_BUILD_DIR%
  - if "%CONFIGURATION%"=="Release" echo is_debug=false >> %PDFium_ARGS%
  - if "%PLATFORM%"=="x86" echo target_cpu="x86" >> %PDFium_ARGS%
  - move %PDFium_ARGS% %PDFium_BUILD_DIR%\args.gn
  - gn gen %PDFium_BUILD_DIR%
  - ninja -C %PDFium_BUILD_DIR% pdfium

after_build:
  - mkdir %PDFium_STAGING_DIR%
  - move PDFiumConfig.cmake %PDFium_STAGING_DIR%
  - move %PDFium_SOURCE_DIR%\LICENSE %PDFium_STAGING_DIR%
  - move %PDFium_SOURCE_DIR%\public %PDFium_INCLUDE_DIR%
  - del %PDFium_INCLUDE_DIR%\DEPS
  - del %PDFium_INCLUDE_DIR%\README
  - mkdir %PDFium_LIB_DIR%
  - move %PDFium_BUILD_DIR%\pdfium.dll.lib %PDFium_LIB_FILE%
  - move %PDFium_BUILD_DIR%\pdfium.dll %PDFium_DLL_FILE%
  - if "%CONFIGURATION%"=="debug" move %PDFium_BUILD_DIR%\pdfium.dll.pdb %PDFium_PDB_FILE%
  - cd %PDFium_STAGING_DIR%
  - 7z a %PDFium_ARTIFACT% *

artifacts:
  - path: pdfium-*.zip
    name: PDFium library

deploy:
  - provider: GitHub
    tag: latest
    release: 'Latest build from master'
    description: "This is the latest build from the 'master' branch"
    prerelease: true
    force_update: true
    auth_token:
      secure: JH8IVbdgVLz16ZXQLO41jQ5OsC7wR8IMRPAzinrdqpvgfhe/btgtr1xZ5trO2Eux
    on:
      branch: master
