name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - chromium/*

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-20.04
            v8: disabled
            cfg: Release
            cpu: x64
            artifact: pdfium-linux-x64
          - runner: ubuntu-20.04
            v8: disabled
            cfg: Release
            cpu: arm
            artifact: pdfium-linux-arm
            install: g++-arm-linux-gnueabihf
            skip_test: true
          - runner: macos-10.15
            v8: disabled
            cfg: Release
            cpu: x64
            artifact: pdfium-darwin-x64
          - runner: macos-10.15
            v8: disabled
            cfg: Release
            cpu: arm64
            artifact: pdfium-darwin-arm64
            skip_test: true
          - runner: windows-2019
            v8: disabled
            cfg: Release
            cpu: x86
            artifact: pdfium-windows-x86
          - runner: windows-2019
            v8: disabled
            cfg: Release
            cpu: x64
            artifact: pdfium-windows-x64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Install
        if: ${{ matrix.install }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.install }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set PDFium branch
        if: ${{ startsWith(github.ref, 'refs/tags/chromium/') }}
        run: echo "PDFium_BRANCH=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build
        run: ./build.sh
        shell: bash
        env:
          PDFium_V8: ${{ matrix.v8 }}
          CONFIGURATION: ${{ matrix.cfg }}
          TARGET_CPU: ${{ matrix.cpu }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: staging/
      - name: Test
        run: ./test.sh
        shell: bash
        if: ${{ !matrix.skip_test }}
        env:
          TARGET_CPU: ${{ matrix.cpu }}
      - name: Upload tarball to GitHub Release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/chromium/') }}
        with:
          allowUpdates: true
          draft: true
          artifacts: pdfium*.tgz
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish Release
    if: ${{ startsWith(github.ref, 'refs/tags/chromium/') }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Write release body
      run: echo "This version was built with branch ${GITHUB_REF#refs/tags/} of PDFium" > RELEASE.md
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        bodyFile: RELEASE.md
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}
